### PR TITLE
Fix misc.py import for confusion matrix plot

### LINKED ISSUE #52: Error printing out confusion matrix
Hi, I'm encountering errors when trying to print out the confusion matrix when training diploSHIC.

Minimal code:
If I simply want to run the training command on mosquito simulation data, as provided in your tutorial, but also outputting the confusion matrix:

`diploSHIC train trainingSets/ trainingSets/ bfsModel --confusionFile ConfusionMatrix`

I get the following error message:

```
Traceback (most recent call last):
  File "/ceph/users/mhartfield/.conda/envs/diploshic/bin/diploSHIC", line 537, in <module>
    from misc import plot_confusion_matrix
ModuleNotFoundError: No module named 'misc'
```

I looked at the 'diploSHIC' python file in the repo and there is no 'import misc' command; I added such a command to the end of the other 'import' commands but there is still an error message.

Program was run on a linux-based cluster.

### PR DESCRIPTION
**Pull request by bruce-edelman**
This fixes #52 by changing the import statement for misc.py to plot confusion matrix from the main diploSHIC script

### CODE REVIEW

**Comment by andrewkern** [comment]
LGTM, but we are getting some error with the actions. any clue what's up with that?

**Comment by bruce-edelman** [comment]
> LGTM, but we are getting some error with the actions. any clue what's up with that?

Weird -- it is failing to build numpy when doing a pip install to build the wheel. It shows that the version of gcc on the machine it is running on to be 8.3.1 but requires >= 8.4 to build numpy. I think updating the docker image that the wheels are built in will fix this. I will try that out and add that to this PR

**Comment by bruce-edelman** [comment]
okay this should now be good to go @andrewkern 

Yesterday was weird as  I updated the manylinux docker image to one with newer gcc versions and the build passed once. Afterwards it failed many times over from a weird error downloading the remote docker image. 

Today after just rerunning the CI it seems to have worked again so there must have been server issues yesterday that are now fixed. The reason the pull_request version of the PyPI upload failed was because a wheel for version 1.0.5 already exists from the "push" version of the PyPI upload job that succeeded. 

Not that it is too important but I think in my PR with domain adaptation I had tried to split up the github action jobs so that the PyPI uploading only happens once and thus doesn't cause subsequent jobs with same version numbers to fail.

**Comment by andrewkern** [comment]
okay sounds good @bruce-edelman -- I'll merge this. what do you reckon we should do with the domain adaptation PR? Should we split out the action edits to another PR?

**Comment by bruce-edelman** [comment]
Sure that sounds good to me  @andrewkern -- I do that and create another PR with the changes to the actions

**Comment by andrewkern** [comment]
arg... looks like the upload to pypi failed, presumably because the version number needs to be bumped?

**Comment by bruce-edelman** [comment]
> arg... looks like the upload to pypi failed, presumably because the version number needs to be bumped?

I actually think it worked. Its just currently configured to run twice. Once on the push and once for the pull request -- so once completed and then the second failed because there was already a v1.0.5 published to PyPI -- [diploshics PyPI page](https://pypi.org/project/diploSHIC/#history) showed 1.0.5 recently uploaded

**Comment by andrewkern** [comment]
okay awesome!

**Pull request merged**
